# Generated by Django 6.0.3 on 2026-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0002_product_article_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, help_text='Артикул товара (например, RG-001)', max_length=50, null=True),
        ),
    ]
