# Generated by Django 6.0.3 on 2026-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0003_alter_product_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Код из Excel (TPZ, EMD, etc.)', max_length=20, unique=True)),
                ('color', models.CharField(blank=True, help_text='HEX цвет для отображения', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Stones',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='stone_type',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL изображения из интернета'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddField(
            model_name='product',
            name='stones',
            field=models.ManyToManyField(blank=True, related_name='products', to='jewelry_app.stone'),
        ),
    ]
