# Generated by Django 6.0.3 on 2026-03-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0004_stone_remove_product_stone_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ring_size',
            field=models.CharField(blank=True, help_text='Размер кольца (для колец)', max_length=20, null=True),
        ),
    ]
