# Generated by Django 6.0.3 on 2026-04-04 09:12

import jewelry_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0006_brand_product_reference_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=jewelry_app.utils.get_brand_logo_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, help_text='Артикул товара (например, RG-001)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=jewelry_app.utils.get_product_image_path),
        ),
    ]
