# Generated by Django 6.0.3 on 2026-04-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0007_remove_product_reference_remove_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_stones',
        ),
    ]
