# Generated by Django 6.0.3 on 2026-04-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0008_remove_product_has_stones'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metal',
            field=models.CharField(blank=True, choices=[('gold', 'Золото'), ('white_gold', 'Белое золото'), ('rose_gold', 'Розовое золото'), ('silver', 'Серебро'), ('platinum', 'Платина'), ('steel', 'Сталь'), ('titanium', 'Титан')], help_text='Основной металл', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_purity',
            field=models.CharField(blank=True, help_text='Проба металла', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Дополнительное описание материала', max_length=100),
        ),
    ]
