# Generated by Django 6.0.3 on 2026-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0009_product_metal_product_metal_purity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(blank=True, help_text='URL изображения (локальный или внешний)', max_length=500),
        ),
    ]
